### ISSUE TITLE
async without await is dangerous

### ISSUE THREAD

**Issue by LouisCAD** [venkatperi/kotlin-coroutines-lib#1]
https://github.com/venkatperi/kotlin-coroutines-lib/blob/b0701804100e92da70f935c36d6fc3662dd8b22d/src/main/kotlin/com/vperi/kotlinx/coroutines/experimental/JobIterables.ext.kt#L19
The `forEachAsync` should return a `Deferred` which you can `await` that would throw any exception. The current implementation keeps them silent, which is very dangerous. Also, there's no way to know when all the iterations are done.

**Comment by venkatperi** [comment]
True, I dropped that extension for now -- I'm unsure of what the semantics should be.
